HEIGHT = 800
WIDTH = 600

TITLE = "Maze Solver"

MAZE_TOP_LEFT = (1, 1)
CELL_SIZE_X = 100
CELL_SIZE_Y = 100
MAX_ROWS = 3  # HEIGHT // CELL_SIZE_X - MAZE_TOP_LEFT[0]
MAX_COLUMNS = 3  # WIDTH // CELL_SIZE_Y - MAZE_TOP_LEFT[1]
MAX_SLEEP_TIME = 0.01
